// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1//transaction/reconcile": {
            "post": {
                "description": "Reconcile Transaction between system and bank transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loan"
                ],
                "summary": "Reconcile Transaction between system and bank transaction",
                "parameters": [
                    {
                        "description": "ReconcileTransaction payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ReconcileTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.ReconcileTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helper.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.BankTransaction": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "bank_name": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "unique_identifier": {
                    "type": "string"
                }
            }
        },
        "entity.ReconcileTransactionDetail": {
            "type": "object",
            "properties": {
                "percentage": {
                    "type": "number"
                },
                "total_transaction_matched": {
                    "type": "integer"
                },
                "total_transaction_processed": {
                    "type": "integer"
                },
                "total_transaction_unmatched": {
                    "type": "integer"
                },
                "unmatched_transaction_detail": {
                    "$ref": "#/definitions/entity.UnmatchedTransactionDetail"
                }
            }
        },
        "entity.ReconcileTransactionRequest": {
            "type": "object",
            "properties": {
                "bank_transaction_paths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "end_date": {
                    "type": "string"
                },
                "is_async": {
                    "type": "boolean"
                },
                "start_date": {
                    "type": "string"
                },
                "system_transaction_path": {
                    "type": "string"
                }
            }
        },
        "entity.ReconcileTransactionResponse": {
            "type": "object",
            "properties": {
                "progress_detail_url": {
                    "type": "string"
                },
                "progress_percentage": {
                    "type": "number"
                },
                "progress_status": {
                    "type": "string"
                },
                "reconcile_transaction_detail": {
                    "$ref": "#/definitions/entity.ReconcileTransactionDetail"
                },
                "serial": {
                    "type": "string"
                }
            }
        },
        "entity.SystemTransaction": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "transactionTime": {
                    "type": "string"
                },
                "trxID": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "entity.UnmatchedTransactionDetail": {
            "type": "object",
            "properties": {
                "unmatched_bank_transaction": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/entity.BankTransaction"
                        }
                    }
                },
                "unmatched_system_transaction": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.SystemTransaction"
                    }
                }
            }
        },
        "helper.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
